# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: /
    weight: 10
  - name: CV
    url: a-propos/
    weight: 20
  - name: Danse
    url: /#danse
    weight: 30
  - name: Soins énergétiques
    url: /#soins-energetiques
    weight: 40
